version: '3'
services:
  kong-database:
    image: postgres:9.4
    container_name: kong-postgres
    restart: always
    networks:
      bridge-kong:
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  
  # Kong
  kong:
    image: kong
    container_name: kong-gateway
    restart: always
    networks:
      bridge-kong:
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    expose:
      - 7946
      - 7946/udp
    volumes:
      - ./config/kong.conf:/etc/kong/kong.conf
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database

networks:
  bridge-kong:
    external:
      name: micro-kong